// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzwbjrfwexvvufyvyjjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6d2JqcmZ3ZXh2dnVmeXZ5amp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODQ0NjUsImV4cCI6MjA3MTM2MDQ2NX0.Z3bGkZP_IzjiL6HlpFqJNRkDQgDged4f17C3Ignzr6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});